name: agh6db
services:
  northwind:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
    volumes:
      - ./src/main/resources/db-schema/db-schema.sql:/docker-entrypoint-initdb.d/2_db-schema.sql
      - ./src/main/resources/db-schema/data.sql:/docker-entrypoint-initdb.d/3_data.sql
      #- database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  northwind-java:
    depends_on:
       - northwind
    build: .
    ports:
      - 8080:8080
    networks:
      - postgres

volumes:
  database-data: 

networks:
  postgres:
    driver: bridge
