name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1.0.1
        with:
          input_dir: docs
          output_dir: pdfs
          images_path: .
          images_dir: docs
          build_html: false
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
           commit_message: Auto pdf changes
     
