name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mkrakowitzer/actions-makepdfs@master
      if: github.ref == 'refs/heads/master'
      with:
        markdown_dir: docs
        output_dir: pdfs
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto pdf changes
